# Generated by Django 3.1.3 on 2021-10-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
