# Generated by Django 3.1.3 on 2021-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_category_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup_lan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup_lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='pickup_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
