# Generated by Django 3.1.3 on 2021-10-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_auto_20211025_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='pickup_lan',
            new_name='pickup_lng',
        ),
    ]
